EepromEntry eeprom_map_sailfish_7_7[] = {
{ "ACCELERATION_ACTIVE", "Acceleration active", "", 0x16e, et_byte, 0, 1,
  "Check or set to 1 to use acceleration.  Uncheck or set to 0 for no acceleration.  Note that you must turn acceleration on to print safely at speeds over 50mm/s." },
{ "MAX_ACCELERATION_EXTRUDER_MOVE", "Max acceleration extruder move", "mm/s²", 0x186, et_ushort, 0, 0,
  "" },
{ "MAX_SPEED_CHANGE_X", "Max speed change x", "mm/s", 0x17c, et_fixed, 0, 0,
  "" },
{ "MAX_SPEED_CHANGE_Y", "Max speed change y", "mm/s", 0x180, et_fixed, 0, 0,
  "" },
{ "MAX_SPEED_CHANGE_Z", "Max speed change z", "mm/s", 0x184, et_fixed, 0, 0,
  "" },
{ "MAX_SPEED_CHANGE_A", "Max speed change a", "mm/s", 0x188, et_fixed, 0, 0,
  "" },
{ "MAX_SPEED_CHANGE_B", "Max speed change b", "mm/s", 0x18c, et_fixed, 0, 0,
  "" },
{ "MAX_ACCELERATION_AXIS_X", "Max acceleration axis x", "mm/s²", 0x186, et_ushort, 0, 0,
  "" },
{ "MAX_ACCELERATION_AXIS_Y", "Max acceleration axis y", "mm/s²", 0x188, et_ushort, 0, 0,
  "" },
{ "MAX_ACCELERATION_AXIS_Z", "Max acceleration axis z", "mm/s²", 0x18a, et_ushort, 0, 0,
  "" },
{ "MAX_ACCELERATION_AXIS_A", "Max acceleration axis a", "mm/s²", 0x18c, et_ushort, 0, 0,
  "" },
{ "MAX_ACCELERATION_AXIS_B", "Max acceleration axis b", "mm/s²", 0x18e, et_ushort, 0, 0,
  "" },
{ "MAX_ACCELERATION_NORMAL_MOVE", "Max acceleration normal move", "mm/s²", 0x18e, et_ushort, 0, 0,
  "" },
{ "ALEVEL_PROBE_COMP_SETTINGS_P1", "Alevel probe comp settings p1", "steps", 0xf51, et_long, 0, 0,
  "The deflection compensation values for each of the auto-leveling probing points, P1, P2, and P3.  These values are stored in units of Z axis steps." },
{ "ALEVEL_PROBE_COMP_SETTINGS_P2", "Alevel probe comp settings p2", "steps", 0xf55, et_long, 0, 0,
  "The deflection compensation values for each of the auto-leveling probing points, P1, P2, and P3.  These values are stored in units of Z axis steps." },
{ "ALEVEL_PROBE_COMP_SETTINGS_P3", "Alevel probe comp settings p3", "steps", 0xf59, et_long, 0, 0,
  "The deflection compensation values for each of the auto-leveling probing points, P1, P2, and P3.  These values are stored in units of Z axis steps." },
{ "EXTRUDER_DEPRIME_ON_TRAVEL", "Extruder deprime on travel", "", 0x217, et_byte, 0, 1,
  "When set, the firmware will deprime the extruder on detected travel moves as well as on pauses, planned or otherwise.  When not set, the firmware will only deprime the extruder on pauses, planned or otherwise.  Unplanned pauses occur when the acceleration planner falls behind and the printer waits briefly for another segment to print." },
{ "CLEAR_FOR_ESTOP", "Clear for estop", "", 0xf9a, et_byte, 0, 1,
  "Check or set to 1 to instruct the printer to clear the build away from the extruder before stopping.  Uncheck or set to zero to immediately stop the printer (e.g., perform an Emergency Stop)." },
{ "T0_COOLING_ENABLE_OFFSET", "T0 cooling enable offset", "", 0x1a, et_byte, 0, 1,
  "" },
{ "T0_COOLING_SETPOINT_C_OFFSET", "T0 cooling setpoint c offset", "C", 0x1b, et_byte, 0, 300,
  "" },
{ "T0_EXTRUDER_D_TERM_OFFSET", "T0 extruder d term offset", "", 0xe, et_fixed, 0, 100,
  "" },
{ "T0_EXTRUDER_P_TERM_OFFSET", "T0 extruder p term offset", "", 0xa, et_fixed, 0, 100,
  "" },
{ "T0_EXTRUDER_I_TERM_OFFSET", "T0 extruder i term offset", "", 0xc, et_fixed, 0, 1,
  "" },
{ "PREHEAT_PREHEAT_RIGHT_TEMP", "Preheat preheat right temp", "C", 0x158, et_ushort, 0, 280,
  "" },
{ "PREHEAT_PREHEAT_PLATFORM_TEMP", "Preheat preheat platform temp", "C", 0x15c, et_ushort, 0, 130,
  "" },
{ "PREHEAT_PREHEAT_LEFT_TEMP", "Preheat preheat left temp", "C", 0x15a, et_ushort, 0, 280,
  "" },
{ "JKN_ADVANCE_K2", "Jkn advance k2", "factor * 100000", 0x1dc, et_ulong, 0, 0,
  "" },
{ "JKN_ADVANCE_K", "Jkn advance k", "factor * 100000", 0x1d8, et_ulong, 0, 0,
  "" },
{ "EXTRUDER_DEPRIME_STEPS_A", "Extruder deprime steps a", "steps", 0x1e0, et_ushort, 0, 0,
  "" },
{ "EXTRUDER_DEPRIME_STEPS_B", "Extruder deprime steps b", "steps", 0x1e2, et_ushort, 0, 0,
  "" },
{ "SLOWDOWN_FLAG", "Slowdown flag", "", 0x1e8, et_byte, 0, 1,
  "Check or set to 1 to enable automatic print slowdown when the queue of planned segments is running low.  Uncheck or set to 0 to disable automatic slowdown." },
{ "COOLING_FAN_DUTY_CYCLE", "Cooling fan duty cycle", "", 0xf6f, et_byte, 0, 100,
  "Set a blower strength (duty cycle) to use for the print cooling fan when it is activated by the print commands.  Select a value between 0% (off) and 100% (on full).  For example, if your fan is too strong, you may want to set this value to 50 so that the fan operates at 50% strength.  If set this value to 0, then the cooling fan will not activate at all when the print commands request it to." },
{ "MACHINE_NAME", "Machine name", "", 0x2e, et_string, 0, 0,
  "" },
{ "ALEVEL_MAX_ZDELTA", "Alevel max zdelta", "steps", 0xf72, et_long, 0, 0,
  "The maximum vertical difference between any two probed leveling points may not exceed this value.  Default value is 50 steps (0.5 mm)." },
{ "PSTOP_ENABLE", "Pstop enable", "", 0xf9c, et_byte, 0, 1,
  "Check or set to 1 to enable the optional Pause Stop hardware.  Set to zero or uncheck to disable.  The bot should be power cycled after changing this field." },
{ "DITTO_PRINT_ENABLED", "Ditto print enabled", "", 0x100b, et_byte, 0, 1,
  "Check or set to 1 to enable ditto printing. Uncheck or set to zero to disable ditto printing." },
{ "SD_USE_CRC", "Sd use crc", "", 0xf9d, et_byte, 0, 1,
  "Check or set to 1 to enable SD card error checkin.  Uncheck or set to 0 to disable." },
{ "ALEVEL_MAX_ZPROBE_HITS", "Alevel max zprobe hits", "", 0xf70, et_byte, 0, 200,
  "Trigger a pause if the auto-leveling probe registers too many hits during a print. Set to the value 0 to allow an unlimited number of hits without pausing; otherwise, set to a value in the range 1 to 200." },
{ "AXIS_HOME_DIRECTION", "Axis home direction", "", 0x18, et_bitfield, 0, 0,
  "A Bitfield representing the XYZAB axes, with X as bit 0. If an axis is homing in the wrong direction, toggle the bit for that axis" },
{ "LED_LED_HEAT_OFFSET", "Led led heat offset", "", 0x142, et_byte, 1, 0,
  "" },
{ "LED_CUSTOM_COLOR_OFFSET_R", "Led custom color offset r", "RGB", 0x144, et_byte, 0, 0,
  "" },
{ "LED_CUSTOM_COLOR_OFFSET_G", "Led custom color offset g", "RGB", 0x145, et_byte, 0, 0,
  "" },
{ "LED_CUSTOM_COLOR_OFFSET_B", "Led custom color offset b", "RGB", 0x146, et_byte, 0, 0,
  "" },
{ "LED_BASIC_COLOR_OFFSET", "Led basic color offset", "", 0x143, et_byte, 0, 10,
  "" },
{ "AXIS_HOME_POSITIONS_STEPS_X", "Axis home positions steps x", "steps", 0x1a, et_ulong, 0, 0,
  "" },
{ "AXIS_HOME_POSITIONS_STEPS_Y", "Axis home positions steps y", "steps", 0x1e, et_ulong, 0, 0,
  "" },
{ "AXIS_HOME_POSITIONS_STEPS_Z", "Axis home positions steps z", "steps", 0x22, et_ulong, 0, 0,
  "" },
{ "AXIS_HOME_POSITIONS_STEPS_A", "Axis home positions steps a", "steps", 0x26, et_ulong, 0, 0,
  "" },
{ "AXIS_HOME_POSITIONS_STEPS_B", "Axis home positions steps b", "steps", 0x2a, et_ulong, 0, 0,
  "" },
{ "AXIS_STEPS_PER_MM_X", "Axis steps per mm x", "1,000,000 * steps/mm", 0x1c4, et_ulong, 0, 0,
  "" },
{ "AXIS_STEPS_PER_MM_Y", "Axis steps per mm y", "1,000,000 * steps/mm", 0x1c8, et_ulong, 0, 0,
  "" },
{ "AXIS_STEPS_PER_MM_Z", "Axis steps per mm z", "1,000,000 * steps/mm", 0x1cc, et_ulong, 0, 0,
  "" },
{ "AXIS_STEPS_PER_MM_A", "Axis steps per mm a", "1,000,000 * steps/mm", 0x1d0, et_ulong, 0, 0,
  "" },
{ "AXIS_STEPS_PER_MM_B", "Axis steps per mm b", "1,000,000 * steps/mm", 0x1d4, et_ulong, 0, 0,
  "" },
{ "OVERRIDE_GCODE_TEMP", "Override gcode temp", "", 0x1031, et_byte, 0, 1,
  "Check or set to 1 to override non-zero gcode temperature settings with the pre-heat temperature settings.  Uncheck or set to zero to honor temperature settings in the gcode." },
{ "TOOL_COUNT", "Tool count", "", 0x76, et_byte, 1, 2,
  "" },
{ "TEMP_TABLE_INDICES_TC1", "Temp table indices tc1", "", 0xf79, et_byte, 0, 0,
  "" },
{ "TEMP_TABLE_INDICES_TC2", "Temp table indices tc2", "", 0xf7a, et_byte, 0, 0,
  "" },
{ "TEMP_TABLE_INDICES_TCHBP", "Temp table indices tchbp", "", 0xf7b, et_byte, 0, 0,
  "" },
{ "T1_COOLING_ENABLE_OFFSET", "T1 cooling enable offset", "", 0x1a, et_byte, 0, 1,
  "" },
{ "T1_COOLING_SETPOINT_C_OFFSET", "T1 cooling setpoint c offset", "C", 0x1b, et_byte, 0, 300,
  "" },
{ "T1_EXTRUDER_D_TERM_OFFSET", "T1 extruder d term offset", "", 0xe, et_fixed, 0, 100,
  "" },
{ "T1_EXTRUDER_P_TERM_OFFSET", "T1 extruder p term offset", "", 0xa, et_fixed, 0, 100,
  "" },
{ "T1_EXTRUDER_I_TERM_OFFSET", "T1 extruder i term offset", "", 0xc, et_fixed, 0, 1,
  "" },
{ "BUZZ_SOUND_ON", "Buzz sound on", "", 0x14a, et_byte, 0, 1,
  "Check or set to 1 to play bot sounds.  Uncheck or set to 0 for no sounds." },
{ "HEAT_DURING_PAUSE", "Heat during pause", "", 0x1035, et_byte, 0, 1,
  "Check or set to 1 to leave heaters enabled for up to 30 minutes while the bot is pasued.  Uncheck or set to zero to disable the heaters upon entering a paused state." },
{ "AXIS_INVERSION", "Axis inversion", "", 0x39, et_bitfield, 0, 0,
  "A Bitfield representing the XYZAB axes, with X as bit 0. If an axis is moving in the wrong direction, toggle the bit for that axis" },
{ "DIGI_POT_SETTINGS_X", "Digi pot settings x", "scale(1-118)", 0x3d, et_byte, 0, 0,
  "" },
{ "DIGI_POT_SETTINGS_Y", "Digi pot settings y", "scale(1-118)", 0x3e, et_byte, 0, 0,
  "" },
{ "DIGI_POT_SETTINGS_Z", "Digi pot settings z", "scale(1-118)", 0x3f, et_byte, 0, 0,
  "" },
{ "DIGI_POT_SETTINGS_A", "Digi pot settings a", "scale(1-118)", 0x40, et_byte, 0, 0,
  "" },
{ "DIGI_POT_SETTINGS_B", "Digi pot settings b", "scale(1-118)", 0x41, et_byte, 0, 0,
  "" },
{ "HBP_PRESENT", "Hbp present", "", 0x88, et_byte, 0, 1,
  "Check or set to 1 if this machine has a heated build platform; otherwise, uncheck or set to 0 if it does not.  The bot should be power cycled after changing this field." },
{ "ALEVEL_PROBE_OFFSETS_X", "Alevel probe offsets x", "steps", 0xf85, et_long, 0, 0,
  "The X and Y displacements of the auto-leveling Z probe from the extruder nozzle.  negative X values are to the left of the nozzle while positive X values are to the right.  Negative Y values are in front of the nozzle while positive Y values are behind the nozzle." },
{ "ALEVEL_PROBE_OFFSETS_Y", "Alevel probe offsets y", "steps", 0xf89, et_long, 0, 0,
  "The X and Y displacements of the auto-leveling Z probe from the extruder nozzle.  negative X values are to the left of the nozzle while positive X values are to the right.  Negative Y values are in front of the nozzle while positive Y values are behind the nozzle." },
{ "TOOLHEAD_OFFSET_SYSTEM", "Toolhead offset system", "", 0xfd7, et_byte, 0, 1,
  "Check to use the NEW dualstrusion system. Uncheck to use the old (RepG 39 and earlier) dualstrusion system.  The bot should be power cycled after changing this field." },
{ "TOOLHEAD_OFFSET_SETTINGS_X", "Toolhead offset settings x", "steps", 0x1a6, et_long, -2000, 20000,
  "" },
{ "TOOLHEAD_OFFSET_SETTINGS_Y", "Toolhead offset settings y", "steps", 0x1aa, et_long, -2000, 20000,
  "" },
{ "PSTOP_INVERTED", "Pstop inverted", "", 0xf94, et_byte, 0, 1,
  "Check if the P-Stop switch is an inverted switch and goes HIGH when triggered and LOW when not triggered.  Uncheck if using a typical endstop switch which goes LOW when triggered." },
{ "EXTRUDER_HOLD", "Extruder hold", "", 0xfde, et_byte, 0, 1,
  "Check or set to 1 to enable the Extruder Hold feature.  Uncheck or set to 0 to disable." },
};
