EepromMapping eeprom_map_sailfish_4_7[] = {
{ "ACCELERATION_ACTIVE", "Acceleration active", "", 0x126, et_boolean, 0, 0, 1,
  "Check or set to 1 to use acceleration.  Uncheck or set to 0 for no acceleration.  Note that you must turn acceleration on to print safely at speeds over 50mm/s.", 1.0 },
{ "MAX_ACCELERATION_EXTRUDER_MOVE", "Max acceleration extruder move", "mm/s²", 0x14B, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "MAX_SPEED_CHANGE_X", "Max speed change x", "mm/s", 0x192, et_long, 0, 0, 0,
  "", 10.0 },
{ "MAX_SPEED_CHANGE_Y", "Max speed change y", "mm/s", 0x196, et_long, 0, 0, 0,
  "", 10.0 },
{ "MAX_SPEED_CHANGE_Z", "Max speed change z", "mm/s", 0x19A, et_long, 0, 0, 0,
  "", 10.0 },
{ "MAX_SPEED_CHANGE_A", "Max speed change a", "mm/s", 0x19E, et_long, 0, 0, 0,
  "", 10.0 },
{ "MAX_SPEED_CHANGE_B", "Max speed change b", "mm/s", 0x1A2, et_long, 0, 0, 0,
  "", 10.0 },
{ "MAX_ACCELERATION_AXIS_X", "Max acceleration axis x", "mm/s²", 0x13B, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "MAX_ACCELERATION_AXIS_Y", "Max acceleration axis y", "mm/s²", 0x13F, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "MAX_ACCELERATION_AXIS_Z", "Max acceleration axis z", "mm/s²", 0x143, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "MAX_ACCELERATION_AXIS_A", "Max acceleration axis a", "mm/s²", 0x147, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "MAX_ACCELERATION_AXIS_B", "Max acceleration axis b", "mm/s²", 0x1A6, et_ulong, 0, 0, 0,
  "", 1.0 },
/*{ "MAX_ACCELERATION_NORMAL_MOVE", "Max acceleration normal move", "mm/s²", 0x14B, et_ushort, 0, 0, 0,
  "", 1.0 },*/
{ "EXTRUDER_DEPRIME_ON_TRAVEL", "Extruder deprime on travel", "", 0x1EE, et_boolean, 0, 0, 1,
  "When set, the firmware will deprime the extruder on detected travel moves as well as on pauses, planned or otherwise.  When not set, the firmware will only deprime the extruder on pauses, planned or otherwise.  Unplanned pauses occur when the acceleration planner falls behind and the printer waits briefly for another segment to print.", 1.0 },
{ "ALEVEL_MAX_ZPROBE_HITS", "Alevel max zprobe hits", "", 0x1F0, et_byte, 0, 0, 200,
  "Trigger a pause if the auto-leveling probe registers too many hits during a print. Set to the value 0 to allow an unlimited number of hits without pausing; otherwise, set to a value in the range 1 to 200.", 1.0 },
/*{ "T0_COOLING_SETPOINT_C", "T0 cooling setpoint c", "C", 0x11b, et_byte, 0, 0, 300,
  "", 1.0 },
{ "T0_COOLING_ENABLE", "T0 cooling enable", "", 0x11a, et_boolean, 0, 0, 1,
  "", 1.0 },
{ "T0_EXTRUDER_P_TERM", "T0 extruder p term", "", 0x10a, et_fixed, 0, 0, 100,
  "", 1.0 },
{ "T0_EXTRUDER_I_TERM", "T0 extruder i term", "", 0x10c, et_fixed, 0, 0, 1,
  "", 1.0 },
{ "T0_EXTRUDER_D_TERM", "T0 extruder d term", "", 0x10e, et_fixed, 0, 0, 100,
  "", 1.0 },
{ "HBP_P_TERM", "Heatbed p term", "", 0x110, et_fixed, 0, 0, 100,
  "", 1.0 },
{ "HBP_I_TERM", "T0 extruder i term", "", 0x112, et_fixed, 0, 0, 1,
  "", 1.0 },
{ "HBP_D_TERM", "T0 extruder d term", "", 0x114, et_fixed, 0, 0, 100,
  "", 1.0 },*/
{ "PREHEAT_PREHEAT_RIGHT_TEMP", "Preheat preheat right temp (TOOL0)", "C", 0x80, et_byte, 0, 0, 255,
  "", 1.0 },
{ "PREHEAT_PREHEAT_PLATFORM_TEMP", "Preheat preheat platform temp", "C", 0x82, et_byte, 0, 0, 130,
  "", 1.0 },
{ "PREHEAT_PREHEAT_LEFT_TEMP", "Preheat preheat left temp (TOOL1)", "C", 0x81, et_byte, 0, 0, 255,
  "", 1.0 },
{ "JKN_ADVANCE_K2", "Jkn advance k2", "factor", 0x15F, et_ulong, 0, 0, 0,
  "", 100000.0 },
{ "JKN_ADVANCE_K", "Jkn advance k", "factor", 0x167, et_ulong, 0, 0, 0,
  "", 100000.0 },
{ "EXTRUDER_DEPRIME_STEPS_A", "Extruder deprime steps a", "steps", 0x185, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "EXTRUDER_DEPRIME_STEPS_B", "Extruder deprime steps b", "steps", 0x1AA, et_ulong, 0, 0, 0,
  "", 1.0 },
{ "SLOWDOWN_FLAG", "Slowdown flag", "", 0x189, et_boolean, 0, 0, 1,
  "Check or set to 1 to enable automatic print slowdown when the queue of planned segments is running low.  Uncheck or set to 0 to disable automatic slowdown.", 1.0 },
/*{ "COOLING_FAN_DUTY_CYCLE", "Cooling fan duty cycle", "", 0xf63, et_byte, 0, 0, 100,
  "Set a blower strength (duty cycle) to use for the print cooling fan when it is activated by the print commands.  Select a value between 0% (off) and 100% (on full).  For example, if your fan is too strong, you may want to set this value to 50 so that the fan operates at 50% strength.  If set this value to 0, then the cooling fan will not activate at all when the print commands request it to.", 1.0 },*/
{ "MACHINE_NAME", "Machine name", "", 0x20, et_string, 16, 0, 0,
  "", 1.0 },
{ "ALEVEL_MAX_ZDELTA", "Alevel max zdelta", "steps", 0x1F2, et_long, 0, 0, 0,
  "The maximum vertical difference between any two probed leveling points may not exceed this value.  Default value is 50 steps (0.5 mm).", 1.0 },
{ "PSTOP_ENABLE", "Pstop enable", "", 0x1EC, et_boolean, 0, 0, 1,
  "Check or set to 1 to enable the optional Pause Stop hardware.  Set to zero or uncheck to disable.  The bot should be power cycled after changing this field.", 1.0 },
{ "DITTO_PRINT_ENABLED", "Ditto print enabled", "", 0x1DC, et_boolean, 0, 0, 1,
  "Check or set to 1 to enable ditto printing. Uncheck or set to zero to disable ditto printing.", 1.0 },
{ "SD_USE_CRC", "Sd use crc", "", 0x1EB, et_boolean, 0, 0, 1,
  "Check or set to 1 to enable SD card error checkin.  Uncheck or set to 0 to disable.", 1.0 },
{ "CLEAR_FOR_ESTOP", "Clear for estop", "", 0x1EF, et_boolean, 0, 0, 1,
  "Check or set to 1 to instruct the printer to clear the build away from the extruder before stopping.  Uncheck or set to zero to immediately stop the printer (e.g., perform an Emergency Stop).", 1.0 },
/*{ "AXIS_HOME_DIRECTION", "Axis home direction", "", 0xc, et_bitfield, 0, 0, 0,
  "A Bitfield representing the XYZAB axes, with X as bit 0. If an axis is homing in the wrong direction, toggle the bit for that axis", 1.0 },
{ "LED_LED_HEAT", "Led led heat", "", 0x142, et_byte, 0, 1, 0,
  "", 1.0 },
{ "LED_BASIC_COLOR", "Led basic color", "", 0x140, et_byte, 0, 0, 10,
  "", 1.0 },
{ "LED_CUSTOM_COLOR_R", "Led custom color r", "RGB", 0x144, et_byte, 0, 0, 0,
  "", 1.0 },
{ "LED_CUSTOM_COLOR_G", "Led custom color g", "RGB", 0x145, et_byte, 0, 0, 0,
  "", 1.0 },
{ "LED_CUSTOM_COLOR_B", "Led custom color b", "RGB", 0x146, et_byte, 0, 0, 0,
  "", 1.0 },*/
{ "AXIS_HOME_POSITIONS_STEPS_X", "Axis home positions steps x", "steps", 0x60, et_long, 0, 0, 0,
  "", 1.0 },
{ "AXIS_HOME_POSITIONS_STEPS_Y", "Axis home positions steps y", "steps", 0x64, et_long, 0, 0, 0,
  "", 1.0 },
{ "AXIS_HOME_POSITIONS_STEPS_Z", "Axis home positions steps z", "steps", 0x68, et_long, 0, 0, 0,
  "", 1.0 },
{ "AXIS_HOME_POSITIONS_STEPS_A", "Axis home positions steps a", "steps", 0x6C, et_long, 0, 0, 0,
  "", 1.0 },
{ "AXIS_HOME_POSITIONS_STEPS_B", "Axis home positions steps b", "steps", 0x70, et_long, 0, 0, 0,
  "", 1.0 },
{ "AXIS_STEPS_PER_MM_X", "Axis steps per mm x", "steps/mm", 0x8b, et_long_long, 0, 0, 0,
  "", 10000000000.0 },
{ "AXIS_STEPS_PER_MM_Y", "Axis steps per mm y", "steps/mm", 0x93, et_long_long, 0, 0, 0,
  "", 10000000000.0 },
{ "AXIS_STEPS_PER_MM_Z", "Axis steps per mm z", "steps/mm", 0x9b, et_long_long, 0, 0, 0,
  "", 10000000000.0 },
{ "AXIS_STEPS_PER_MM_A", "Axis steps per mm a", "steps/mm", 0xa3, et_long_long, 0, 0, 0,
  "", 10000000000.0 },
{ "AXIS_STEPS_PER_MM_B", "Axis steps per mm b", "steps/mm", 0xab, et_long_long, 0, 0, 0,
  "", 10000000000.0 },
{ "OVERRIDE_GCODE_TEMP", "Override gcode temp", "", 0xc5, et_boolean, 0, 0, 1,
  "Check or set to 1 to override non-zero gcode temperature settings with the pre-heat temperature settings.  Uncheck or set to zero to honor temperature settings in the gcode.", 1.0 },
{ "ENDSTOP_INVERSION", "Endstop inversion", "", 0x3, et_bitfield, 0, 0, 0,
  "", 1.0 },
{ "TOOL_COUNT", "Tool count", "", 0x1AE, et_byte, 0, 1, 2,
  "", 1.0 },
/*{ "T1_COOLING_SETPOINT_C", "T1 cooling setpoint c", "C", 0x137, et_byte, 0, 0, 300,
  "", 1.0 },
{ "T1_COOLING_ENABLE", "T1 cooling enable", "", 0x136, et_boolean, 0, 0, 1,
  "", 1.0 },
{ "T1_EXTRUDER_P_TERM", "T1 extruder p term", "", 0x126, et_fixed, 0, 0, 100,
  "", 1.0 },
{ "T1_EXTRUDER_I_TERM", "T1 extruder i term", "", 0x128, et_fixed, 0, 0, 1,
  "", 1.0 },
{ "T1_EXTRUDER_D_TERM", "T1 extruder d term", "", 0x12a, et_fixed, 0, 0, 100,
  "", 1.0 },
{ "BUZZ_SOUND_ON", "Buzz sound on", "", 0x14a, et_boolean, 0, 0, 1,
  "Check or set to 1 to play bot sounds.  Uncheck or set to 0 for no sounds.", 1.0 },
{ "HEAT_DURING_PAUSE", "Heat during pause", "", 0xffe, et_boolean, 0, 0, 1,
  "Check or set to 1 to leave heaters enabled for up to 30 minutes while the bot is pasued.  Uncheck or set to zero to disable the heaters upon entering a paused state.", 1.0 },*/
{ "AXIS_INVERSION", "Axis inversion", "", 0x2, et_bitfield, 0, 0, 0,
  "A Bitfield representing the XYZAB axes, with X as bit 0. If an axis is moving in the wrong direction, toggle the bit for that axis", 1.0 },
/*{ "DIGI_POT_SETTINGS_0", "Digi pot settings 0", "scale(1-118)", 0x6, et_byte, 0, 0, 0,
  "", 1.0 },
{ "DIGI_POT_SETTINGS_1", "Digi pot settings 0", "scale(1-118)", 0x7, et_byte, 0, 0, 0,
  "", 1.0 },
{ "DIGI_POT_SETTINGS_2", "Digi pot settings 0", "scale(1-118)", 0x8, et_byte, 0, 0, 0,
  "", 1.0 },
{ "DIGI_POT_SETTINGS_3", "Digi pot settings 0", "scale(1-118)", 0x9, et_byte, 0, 0, 0,
  "", 1.0 },
{ "DIGI_POT_SETTINGS_4", "Digi pot settings 0", "scale(1-118)", 0xa, et_byte, 0, 0, 0,
  "", 1.0 },
{ "HBP_PRESENT", "Hbp present", "", 0x4c, et_boolean, 0, 0, 1,
  "Check or set to 1 if this machine has a heated build platform; otherwise, uncheck or set to 0 if it does not.  The bot should be power cycled after changing this field.", 1.0 },*/
{ "TOOLHEAD_OFFSET_SYSTEM", "Toolhead offset system", "", 0x1EA, et_boolean, 0, 0, 1,
  "Check to use the NEW dualstrusion system. Uncheck to use the old (RepG 39 and earlier) dualstrusion system.  The bot should be power cycled after changing this field.", 1.0 },
{ "TOOLHEAD_OFFSET_SETTINGS_X", "Toolhead offset settings x", "steps", 0x1B0, et_long, 0, -2000, 20000,
  "", 1.0 },
{ "TOOLHEAD_OFFSET_SETTINGS_Y", "Toolhead offset settings y", "steps", 0x1B4, et_long, 0, -2000, 20000,
  "", 1.0 },
{ "EXTRUDER_HOLD", "Extruder hold", "", 0x1E9, et_boolean, 0, 0, 1,
  "Check or set to 1 to enable the Extruder Hold feature.  Uncheck or set to 0 to disable.", 1.0 },
};

// Offsets from https://www.thingiverse.com/thing:32084/files 'sailfish_makerware_eeprom_maps'
// or https://github.com/jetty840/Sailfish-G3Firmware/blob/master/firmware/src/Motherboard/EepromMap.hh

// Everything tool/extruder related can't be easily mapped here:
// The extruder controller is a separate board with its own eeprom.
// Its eeprom map is here: https://github.com/jetty840/Sailfish-G3Firmware/blob/master/firmware/src/Extruder/EepromMap.hh
// One needs to use the HOST_CMD_TOOL_QUERY command to read from it, see:
// https://github.com/jetty840/ReplicatorG/blob/master/src/replicatorg/drivers/gen3/Sanguino3GDriver.java#L2075
// https://github.com/jetty840/Sailfish-G3Firmware/blob/master/firmware/src/Motherboard/Host.cc#L446

// Not used: EEPROM_SIZE, VERSION_LOW, VERSION_HIGH, ESTOP_CONFIGURATION, EXTRUDE_DURATION, EXTRUDE_MMS, MOOD_LIGHT_SCRIPT, MOOD_LIGHT_CUSTOM_RED, MOOD_LIGHT_CUSTOM_GREEN, MOOD_LIGHT_CUSTOM_BLUE, JOG_MODE_SETTINGS, BUZZER_REPEATS, FILAMENT_LIFETIME_A, FILAMENT_TRIP_A, ABP_COPIES, UNUSED1, PROFILE_BASE, ACCEL_MAX_EXTRUDER_RETRACT, UNUSED2, UNUSED3, UNUSED4, UNUSED5, UNUSED6, UNUSED7, LCD_TYPE, ENDSTOPS_USED, HOMING_FEED_RATE_X, HOMING_FEED_RATE_Y, HOMING_FEED_RATE_Z, UNUSED8, UNUSED9, UNUSED10, UNUSED11, AXIS_LENGTHS, FILAMENT_LIFETIME_B, FILAMENT_TRIP_B, VID_PID_INFO, ENDSTOP_Z_MIN
